import 'package:flutter/material.dart';
import 'package:personal_hub_app/domain/entities/emotion_ids.dart';
import 'package:personal_hub_app/l10n/app_localizations.dart';

class EmotionUiModel {
    final String id;
    final Color color;
    final List<EmotionUiModel> children;

    const EmotionUiModel({
        required this.id,
        required this.color,
        this.children = const [],
    });

    /// Returns the localized name for this emotion using the provided [context].
    /// Switches by EmotionIds constants.
    String localizedName(BuildContext context) {
      final l10n = AppLocalizations.of(context)!;
      switch (id) {
        // Happy
        case EmotionIds.happy:
          return l10n.emotion_happy;
        case EmotionIds.happyOptimistic:
          return l10n.emotion_happy_optimistic;
        case EmotionIds.happyOptimisticInspired:
          return l10n.emotion_happy_optimistic_inspired;
        case EmotionIds.happyOptimisticHopeful:
          return l10n.emotion_happy_optimistic_hopeful;
        case EmotionIds.happyTrusting:
          return l10n.emotion_happy_trusting;
        case EmotionIds.happyTrustingIntimate:
          return l10n.emotion_happy_trusting_intimate;
        case EmotionIds.happyTrustingSensitive:
          return l10n.emotion_happy_trusting_sensitive;
        case EmotionIds.happyPeaceful:
          return l10n.emotion_happy_peaceful;
        case EmotionIds.happyPeacefulThankful:
          return l10n.emotion_happy_peaceful_thankful;
        case EmotionIds.happyPeacefulLoving:
          return l10n.emotion_happy_peaceful_loving;
        case EmotionIds.happyPowerful:
          return l10n.emotion_happy_powerful;
        case EmotionIds.happyPowerfulCreative:
          return l10n.emotion_happy_powerful_creative;
        case EmotionIds.happyPowerfulCourageous:
          return l10n.emotion_happy_powerful_courageous;
        case EmotionIds.happyAccepted:
          return l10n.emotion_happy_accepted;
        case EmotionIds.happyAcceptedValued:
          return l10n.emotion_happy_accepted_valued;
        case EmotionIds.happyAcceptedRespected:
          return l10n.emotion_happy_accepted_respected;
        case EmotionIds.happyProud:
          return l10n.emotion_happy_proud;
        case EmotionIds.happyProudConfident:
          return l10n.emotion_happy_proud_confident;
        case EmotionIds.happyProudSuccessful:
          return l10n.emotion_happy_proud_successful;
        case EmotionIds.happyInterested:
          return l10n.emotion_happy_interested;
        case EmotionIds.happyInterestedInquisitive:
          return l10n.emotion_happy_interested_inquisitive;
        case EmotionIds.happyInterestedCurious:
          return l10n.emotion_happy_interested_curious;
        case EmotionIds.happyContent:
          return l10n.emotion_happy_content;
        case EmotionIds.happyContentJoyful:
          return l10n.emotion_happy_content_joyful;
        case EmotionIds.happyContentFree:
          return l10n.emotion_happy_content_free;
        case EmotionIds.happyPlayful:
          return l10n.emotion_happy_playful;
        case EmotionIds.happyPlayfulCheeky:
          return l10n.emotion_happy_playful_cheeky;
        case EmotionIds.happyPlayfulAroused:
          return l10n.emotion_happy_playful_aroused;

        // Angry
        case EmotionIds.angry:
          return l10n.emotion_angry;
        case EmotionIds.angryCritical:
          return l10n.emotion_angry_critical;
        case EmotionIds.angryCriticalDismissive:
          return l10n.emotion_angry_critical_dismissive;
        case EmotionIds.angryCriticalSkeptical:
          return l10n.emotion_angry_critical_skeptical;
        case EmotionIds.angryDistant:
          return l10n.emotion_angry_distant;
        case EmotionIds.angryDistantNumb:
          return l10n.emotion_angry_distant_numb;
        case EmotionIds.angryDistantWithdrawn:
          return l10n.emotion_angry_distant_withdrawn;
        case EmotionIds.angryFrustrated:
          return l10n.emotion_angry_frustrated;
        case EmotionIds.angryFrustratedAnnoyed:
          return l10n.emotion_angry_frustrated_annoyed;
        case EmotionIds.angryFrustratedInfuriated:
          return l10n.emotion_angry_frustrated_infuriated;
        case EmotionIds.angryAggressive:
          return l10n.emotion_angry_aggressive;
        case EmotionIds.angryAggressiveHostile:
          return l10n.emotion_angry_aggressive_hostile;
        case EmotionIds.angryAggressiveProvoked:
          return l10n.emotion_angry_aggressive_provoked;
        case EmotionIds.angryMad:
          return l10n.emotion_angry_mad;
        case EmotionIds.angryMadJealous:
          return l10n.emotion_angry_mad_jealous;
        case EmotionIds.angryMadFurious:
          return l10n.emotion_angry_mad_furious;
        case EmotionIds.angryBitter:
          return l10n.emotion_angry_bitter;
        case EmotionIds.angryBitterViolated:
          return l10n.emotion_angry_bitter_violated;
        case EmotionIds.angryBitterIndignant:
          return l10n.emotion_angry_bitter_indignant;
        case EmotionIds.angryHumiliated:
          return l10n.emotion_angry_humiliated;
        case EmotionIds.angryHumiliatedDisrespected:
          return l10n.emotion_angry_humiliated_disrespected;
        case EmotionIds.angryHumiliatedRidiculed:
          return l10n.emotion_angry_humiliated_ridiculed;
        case EmotionIds.angryLetDown:
          return l10n.emotion_angry_let_down;
        case EmotionIds.angryLetDownResentful:
          return l10n.emotion_angry_let_down_resentful;
        case EmotionIds.angryLetDownBetrayed:
          return l10n.emotion_angry_let_down_betrayed;

        // Sad
        case EmotionIds.sad:
          return l10n.emotion_sad;
        case EmotionIds.sadHurt:
          return l10n.emotion_sad_hurt;
        case EmotionIds.sadHurtEmbarrassed:
          return l10n.emotion_sad_hurt_embarrassed;
        case EmotionIds.sadHurtDisappointed:
          return l10n.emotion_sad_hurt_disappointed;
        case EmotionIds.sadDepressed:
          return l10n.emotion_sad_depressed;
        case EmotionIds.sadDepressedInferior:
          return l10n.emotion_sad_depressed_inferior;
        case EmotionIds.sadDepressedEmpty:
          return l10n.emotion_sad_depressed_empty;
        case EmotionIds.sadGuilty:
          return l10n.emotion_sad_guilty;
        case EmotionIds.sadGuiltyRemorseful:
          return l10n.emotion_sad_guilty_remorseful;
        case EmotionIds.sadGuiltyAshamed:
          return l10n.emotion_sad_guilty_ashamed;
        case EmotionIds.sadDespair:
          return l10n.emotion_sad_despair;
        case EmotionIds.sadDespairPowerless:
          return l10n.emotion_sad_despair_powerless;
        case EmotionIds.sadDespairGrief:
          return l10n.emotion_sad_despair_grief;
        case EmotionIds.sadVulnerable:
          return l10n.emotion_sad_vulnerable;
        case EmotionIds.sadVulnerableFragile:
          return l10n.emotion_sad_vulnerable_fragile;
        case EmotionIds.sadVulnerableVictimized:
          return l10n.emotion_sad_vulnerable_victimized;
        case EmotionIds.sadLonely:
          return l10n.emotion_sad_lonely;
        case EmotionIds.sadLonelyAbandoned:
          return l10n.emotion_sad_lonely_abandoned;
        case EmotionIds.sadLonelyIsolated:
          return l10n.emotion_sad_lonely_isolated;

        // Fearful
        case EmotionIds.fearful:
          return l10n.emotion_fearful;
        case EmotionIds.fearfulScared:
          return l10n.emotion_fearful_scared;
        case EmotionIds.fearfulScaredHelpless:
          return l10n.emotion_fearful_scared_helpless;
        case EmotionIds.fearfulScaredFrightened:
          return l10n.emotion_fearful_scared_frightened;
        case EmotionIds.fearfulAnxious:
          return l10n.emotion_fearful_anxious;
        case EmotionIds.fearfulAnxiousOverwhelmed:
          return l10n.emotion_fearful_anxious_overwhelmed;
        case EmotionIds.fearfulAnxiousWorried:
          return l10n.emotion_fearful_anxious_worried;
        case EmotionIds.fearfulInsecure:
          return l10n.emotion_fearful_insecure;
        case EmotionIds.fearfulInsecureInadequate:
          return l10n.emotion_fearful_insecure_inadequate;
        case EmotionIds.fearfulInsecureInferior:
          return l10n.emotion_fearful_insecure_inferior;
        case EmotionIds.fearfulWeak:
          return l10n.emotion_fearful_weak;
        case EmotionIds.fearfulWeakWorthless:
          return l10n.emotion_fearful_weak_worthless;
        case EmotionIds.fearfulWeakInsignificant:
          return l10n.emotion_fearful_weak_insignificant;
        case EmotionIds.fearfulRejected:
          return l10n.emotion_fearful_rejected;
        case EmotionIds.fearfulRejectedExcluded:
          return l10n.emotion_fearful_rejected_excluded;
        case EmotionIds.fearfulRejectedPersecuted:
          return l10n.emotion_fearful_rejected_persecuted;
        case EmotionIds.fearfulThreatened:
          return l10n.emotion_fearful_threatened;
        case EmotionIds.fearfulThreatenedNervous:
          return l10n.emotion_fearful_threatened_nervous;
        case EmotionIds.fearfulThreatenedExposed:
          return l10n.emotion_fearful_threatened_exposed;

        // Surprised
        case EmotionIds.surprised:
          return l10n.emotion_surprised;
        case EmotionIds.surprisedStartled:
          return l10n.emotion_surprised_startled;
        case EmotionIds.surprisedStartledShocked:
          return l10n.emotion_surprised_startled_shocked;
        case EmotionIds.surprisedStartledDismayed:
          return l10n.emotion_surprised_startled_dismayed;
        case EmotionIds.surprisedConfused:
          return l10n.emotion_surprised_confused;
        case EmotionIds.surprisedConfusedDisillusioned:
          return l10n.emotion_surprised_confused_disillusioned;
        case EmotionIds.surprisedConfusedPerplexed:
          return l10n.emotion_surprised_confused_perplexed;
        case EmotionIds.surprisedAmazed:
          return l10n.emotion_surprised_amazed;
        case EmotionIds.surprisedAmazedAstonished:
          return l10n.emotion_surprised_amazed_astonished;
        case EmotionIds.surprisedAmazedAwe:
          return l10n.emotion_surprised_amazed_awe;
        case EmotionIds.surprisedExcited:
          return l10n.emotion_surprised_excited;
        case EmotionIds.surprisedExcitedEager:
          return l10n.emotion_surprised_excited_eager;
        case EmotionIds.surprisedExcitedEnergetic:
          return l10n.emotion_surprised_excited_energetic;

        // Disgusted
        case EmotionIds.disgusted:
          return l10n.emotion_disgusted;
        case EmotionIds.disgustedDisapproving:
          return l10n.emotion_disgusted_disapproving;
        case EmotionIds.disgustedDisapprovingJudgmental:
          return l10n.emotion_disgusted_disapproving_judgmental;
        case EmotionIds.disgustedDisapprovingEmbarrassed:
          return l10n.emotion_disgusted_disapproving_embarrassed;
        case EmotionIds.disgustedDisappointed:
          return l10n.emotion_disgusted_disappointed;
        case EmotionIds.disgustedDisappointedAppalled:
          return l10n.emotion_disgusted_disappointed_appalled;
        case EmotionIds.disgustedDisappointedRevolted:
          return l10n.emotion_disgusted_disappointed_revolted;
        case EmotionIds.disgustedAwful:
          return l10n.emotion_disgusted_awful;
        case EmotionIds.disgustedAwfulNauseated:
          return l10n.emotion_disgusted_awful_nauseated;
        case EmotionIds.disgustedAwfulDetestable:
          return l10n.emotion_disgusted_awful_detestable;
        case EmotionIds.disgustedRepelled:
          return l10n.emotion_disgusted_repelled;
        case EmotionIds.disgustedRepelledHorrified:
          return l10n.emotion_disgusted_repelled_horrified;
        case EmotionIds.disgustedRepelledHesitant:
          return l10n.emotion_disgusted_repelled_hesitant;

        // Bad
        case EmotionIds.bad:
          return l10n.emotion_bad;
        case EmotionIds.badTired:
          return l10n.emotion_bad_tired;
        case EmotionIds.badTiredSleepy:
          return l10n.emotion_bad_tired_sleepy;
        case EmotionIds.badTiredUnfocused:
          return l10n.emotion_bad_tired_unfocused;
        case EmotionIds.badStressed:
          return l10n.emotion_bad_stressed;
        case EmotionIds.badStressedOutOfControl:
          return l10n.emotion_bad_stressed_out_of_control;
        case EmotionIds.badStressedOverwhelmed:
          return l10n.emotion_bad_stressed_overwhelmed;
        case EmotionIds.badBusy:
          return l10n.emotion_bad_busy;
        case EmotionIds.badBusyPressured:
          return l10n.emotion_bad_busy_pressured;
        case EmotionIds.badBusyRushed:
          return l10n.emotion_bad_busy_rushed;
        case EmotionIds.badBored:
          return l10n.emotion_bad_bored;
        case EmotionIds.badBoredIndifferent:
          return l10n.emotion_bad_bored_indifferent;
        case EmotionIds.badBoredApathetic:
          return l10n.emotion_bad_bored_apathetic;

        default:
          debugPrint('Warning: No localized string found for emotion id: $id');
          return id;
      }
    }
}
